plugins {
    id 'com.android.application'
}

android {
    namespace 'com.aura.os'
    compileSdk 34

    defaultConfig {
        applicationId "com.aura.os"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "2.4.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
        debug {
            minifyEnabled false
        }
    }
}

dependencies {
}
