/**
 * vault.ts — credential & state encryption layer.
 *
 * Defence in depth, two AES-256 layers:
 *   1. JS envelope  : every value is encrypted with AES-256 (CryptoJS) using a
 *      256-bit master key generated by the platform SecureRandom.
 *   2. Disk layer   : the ciphertext is stored through EncryptedSharedPreferences
 *      which re-encrypts values with AES-256-GCM under an Android-Keystore
 *      resident master key (see SecureStorageModule.kt).
 *
 * Nothing sensitive is ever written to plain AsyncStorage.
 */
import CryptoJS from 'crypto-js';
import { SecureStorage } from '../native/Bridge';
import type { NetworkMode, StoredCredentials } from '../types';

const MASTER_KEY_SLOT = 'aitb.masterKey.v1';
const CREDS_SLOT = 'aitb.creds.v1';

let cachedMasterKey: string | null = null;

/** Fetch (or lazily create) the 256-bit master key. */
async function getMasterKey(): Promise<string> {
  if (cachedMasterKey) return cachedMasterKey;
  let mk = await SecureStorage.getItem(MASTER_KEY_SLOT);
  if (!mk) {
    mk = await SecureStorage.randomHex(32); // 32 bytes = 256 bits, platform SecureRandom
    await SecureStorage.setItem(MASTER_KEY_SLOT, mk);
  }
  cachedMasterKey = mk;
  return mk;
}

/** AES-256 encrypt a string with the master key (PBKDF key stretching + salt). */
export function aesEncrypt(plain: string, key: string): string {
  return CryptoJS.AES.encrypt(plain, key).toString();
}

/** AES-256 decrypt; returns null when the payload is corrupt or the key is wrong. */
export function aesDecrypt(cipher: string, key: string): string | null {
  try {
    const bytes = CryptoJS.AES.decrypt(cipher, key);
    const out = bytes.toString(CryptoJS.enc.Utf8);
    return out.length > 0 ? out : null;
  } catch {
    return null;
  }
}

/** Encrypt + persist Binance credentials. */
export async function saveCredentials(creds: {
  apiKey: string;
  secretKey: string;
  mode: NetworkMode;
}): Promise<void> {
  const mk = await getMasterKey();
  const record: StoredCredentials = { ...creds, savedAt: Date.now() };
  const payload = aesEncrypt(JSON.stringify(record), mk);
  await SecureStorage.setItem(CREDS_SLOT, payload);
}

/** Load + decrypt credentials. Returns null when none stored / tampered. */
export async function loadCredentials(): Promise<StoredCredentials | null> {
  const payload = await SecureStorage.getItem(CREDS_SLOT);
  if (!payload) return null;
  const mk = await getMasterKey();
  const plain = aesDecrypt(payload, mk);
  if (!plain) return null;
  try {
    const parsed = JSON.parse(plain) as StoredCredentials;
    if (!parsed.apiKey || !parsed.secretKey) return null;
    return parsed;
  } catch {
    return null;
  }
}

export async function clearCredentials(): Promise<void> {
  await SecureStorage.removeItem(CREDS_SLOT);
}

export async function hasCredentials(): Promise<boolean> {
  return SecureStorage.hasItem(CREDS_SLOT);
}

/** Generic encrypted JSON store for app settings / bot state. */
export async function secureSetJSON<T>(key: string, value: T): Promise<void> {
  const mk = await getMasterKey();
  const payload = aesEncrypt(JSON.stringify(value), mk);
  await SecureStorage.setItem(key, payload);
}

export async function secureGetJSON<T>(key: string): Promise<T | null> {
  const payload = await SecureStorage.getItem(key);
  if (!payload) return null;
  const mk = await getMasterKey();
  const plain = aesDecrypt(payload, mk);
  if (!plain) return null;
  try {
    return JSON.parse(plain) as T;
  } catch {
    return null;
  }
}

export async function secureRemove(key: string): Promise<void> {
  await SecureStorage.removeItem(key);
}

/** SHA-256 helper (used to mask keys in the UI without keeping them). */
export function sha256Hex(input: string): string {
  return CryptoJS.SHA256(input).toString(CryptoJS.enc.Hex);
}

/** HMAC-SHA256 hex signature (Binance request signing). */
export function hmacSha256Hex(message: string, secret: string): string {
  return CryptoJS.HmacSHA256(message, secret).toString(CryptoJS.enc.Hex);
}
