name: DBG apk keystore-only
on:
  push:
    branches: ["**"]
jobs:
  x:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: crypto_trader_app
    steps:
      - name: Decode keystore (optional)
        if: ${{ secrets.ANDROID_KEYSTORE_BASE64 != '' }}
        shell: bash
        run: 'echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

          cat > android/key.properties <<EOF

          storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

          keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}

          keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}

          storeFile=upload-keystore.jks

          EOF

          '
